# Generated by Django 6.0.2 on 2026-02-11 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('forestry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('склад', 'Склад'), ('автомобиль', 'Автомобиль'), ('контрагент', 'Контрагент'), ('бригады', 'Бригада')], max_length=20, verbose_name='Тип хранения')),
                ('source_id', models.IntegerField(verbose_name='ID в исходной таблице')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_storage_location')],
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('accounting_type', models.CharField(choices=[('Перемещение', 'Перемещение'), ('Реализация', 'Реализация'), ('Списание', 'Списание')], max_length=20, verbose_name='Тип учета')),
                ('quantity_pieces', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в штуках')),
                ('quantity_meters', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в погонных метрах')),
                ('quantity_cubic', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в кубических метрах')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('is_completed', models.BooleanField(default=False, help_text='Движение завершено и остатки обновлены', verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор документа')),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'position__name__icontains': 'водитель'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forestry.material', verbose_name='Материал')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vehicle', verbose_name='Транспортное средство')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.storagelocation', verbose_name='Место хранения отправления')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.storagelocation', verbose_name='Место хранения назначения')),
            ],
            options={
                'verbose_name': 'Документ движения материалов',
                'verbose_name_plural': 'Документы движения материалов',
                'indexes': [models.Index(fields=['date_time', 'accounting_type'], name='inventory_m_date_ti_d2f14b_idx'), models.Index(fields=['from_location', 'to_location'], name='inventory_m_from_lo_e148f6_idx'), models.Index(fields=['is_completed'], name='inventory_m_is_comp_374361_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_pieces', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в штуках')),
                ('quantity_meters', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в погонных метрах')),
                ('quantity_cubic', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в кубических метрах')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forestry.material', verbose_name='Материал')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.storagelocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Остаток материала',
                'verbose_name_plural': 'Остатки материалов',
                'indexes': [models.Index(fields=['storage_location', 'material'], name='inventory_m_storage_2df4c3_idx'), models.Index(fields=['material', 'storage_location'], name='inventory_m_materia_16fe51_idx'), models.Index(fields=['last_updated'], name='inventory_m_last_up_47b6be_idx')],
                'constraints': [models.UniqueConstraint(fields=('storage_location', 'material'), name='unique_material_balance')],
            },
        ),
    ]
