# Generated by Django 6.0.2 on 2026-02-25 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='accounting_type',
            field=models.CharField(choices=[('Перемещение', 'Перемещение'), ('Отправление', 'Отправление'), ('Реализация', 'Реализация'), ('Списание', 'Списание')], max_length=20, verbose_name='Тип учета'),
        ),
        migrations.AlterField(
            model_name='materialmovement',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время'),
        ),
    ]
