# Generated by Django 6.0.2 on 2026-02-27 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('inventory', '0002_alter_materialmovement_accounting_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialmovement',
            name='author',
        ),
        migrations.AddField(
            model_name='materialbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_balance', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='materialbalance',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_balance_created', to='core.position', verbose_name='Должность создателя'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_movement', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_movement_created', to='core.position', verbose_name='Должность создателя'),
        ),
    ]
