# Generated by Django 6.0.2 on 2026-03-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_materialmovement_author_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialbalance',
            name='unique_material_balance',
        ),
    ]
