# Generated by Django 6.0.2 on 2026-03-11 10:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('forestry', '0003_cuttingarea_created_by_and_more'),
        ('inventory', '0004_remove_materialbalance_unique_material_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата конвертации')),
                ('source_quantity_pieces', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в штуках (списание)')),
                ('source_quantity_meters', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в погонных метрах (списание)')),
                ('source_quantity_cubic', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в кубических метрах (списание)')),
                ('target_quantity_pieces', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в штуках (создание)')),
                ('target_quantity_meters', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в погонных метрах (создание)')),
                ('target_quantity_cubic', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в кубических метрах (создание)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_completed', models.BooleanField(default=False, help_text='Конвертация выполнена и остатки обновлены', verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversions', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('created_by_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions_created', to='core.position', verbose_name='Должность создателя')),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_source', to='forestry.material', verbose_name='Исходный материал')),
                ('storage_location', models.ForeignKey(limit_choices_to={'source_type': 'склад'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.storagelocation', verbose_name='Место хранения')),
                ('target_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_target', to='forestry.material', verbose_name='Целевой материал')),
            ],
            options={
                'verbose_name': 'Конвертация древесины',
                'verbose_name_plural': 'Конвертации древесины',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversion_date'], name='inventory_c_convers_10d6cb_idx'), models.Index(fields=['storage_location', 'source_material'], name='inventory_c_storage_e10bc2_idx'), models.Index(fields=['is_completed'], name='inventory_c_is_comp_40d47f_idx')],
            },
        ),
    ]
