# Generated by Django 6.0.2 on 2026-03-24 08:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('forestry', '0003_cuttingarea_created_by_and_more'),
        ('inventory', '0005_conversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('quantity_pieces', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в штуках')),
                ('quantity_meters', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в погонных метрах')),
                ('quantity_cubic', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество в кубических метрах')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('created_by_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_created', to='core.position', verbose_name='Должность создателя')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forestry.material', verbose_name='Материал')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_source', to='inventory.storagelocation', verbose_name='Источник поступления')),
                ('storage_location', models.ForeignKey(limit_choices_to={'source_type': 'склад'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.storagelocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Поступление материала',
                'verbose_name_plural': 'Поступления материалов',
                'ordering': ['-receipt_date'],
                'indexes': [models.Index(fields=['receipt_date'], name='inventory_r_receipt_636280_idx'), models.Index(fields=['storage_location', 'material'], name='inventory_r_storage_7fafd4_idx')],
            },
        ),
    ]
