# Generated by Django 6.0.2 on 2026-05-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmovement',
            name='wagon_number',
            field=models.CharField(blank=True, default=None, help_text='Номер железнодорожного вагона', max_length=50, null=True, verbose_name='№ вагона'),
        ),
    ]
