# Generated by Django 6.0.2 on 2026-09-23 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('employees', '0003_employee_created_by_position_and_more'),
        ('forestry', '0003_cuttingarea_created_by_and_more'),
        ('inventory', '0007_materialmovement_wagon_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialmovement',
            index=models.Index(fields=['created_by_position'], name='inventory_m_created_981907_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmovement',
            index=models.Index(fields=['-date_time'], name='inventory_m_date_ti_0d91b5_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmovement',
            index=models.Index(fields=['material', 'is_completed'], name='inventory_m_materia_c2598d_idx'),
        ),
    ]
