# Generated by Django 6.0.2 on 2026-02-11 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forestry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лесничество',
                'verbose_name_plural': 'Лесничества',
            },
        ),
        migrations.CreateModel(
            name='CuttingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_number', models.CharField(max_length=20, verbose_name='Номер квартала')),
                ('division_number', models.CharField(max_length=20, verbose_name='Номер выдела')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь выдела (Га)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('forestry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forestry.forestry', verbose_name='Лесничество')),
            ],
            options={
                'verbose_name': 'Лесосека',
                'verbose_name_plural': 'Лесосеки',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('древесина', 'Древесина'), ('ГСМ', 'ГСМ'), ('запчасти', 'Запчасти')], max_length=20, verbose_name='Вид материала')),
                ('name', models.CharField(max_length=200, verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'constraints': [models.UniqueConstraint(fields=('material_type', 'name'), name='unique_material_type_name')],
            },
        ),
        migrations.CreateModel(
            name='CuttingAreaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('cutting_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.cuttingarea', verbose_name='Лесосека')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forestry.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Содержание лесосеки',
                'verbose_name_plural': 'Содержание лесосек',
            },
        ),
        migrations.AddConstraint(
            model_name='cuttingarea',
            constraint=models.UniqueConstraint(fields=('forestry', 'quarter_number', 'division_number'), name='unique_forestry_quarter_division'),
        ),
        migrations.AddConstraint(
            model_name='cuttingareacontent',
            constraint=models.UniqueConstraint(fields=('cutting_area', 'material'), name='unique_cutting_area_material'),
        ),
    ]
