# Generated by Django 6.0.2 on 2026-02-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brigade_created_by_counterparty_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='created_at',
        ),
    ]
