# Generated by Django 6.0.2 on 2026-02-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_warehouse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brigades_created', to='core.position', verbose_name='Должность создателя'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparties_created', to='core.position', verbose_name='Должность создателя'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_created', to='core.position', verbose_name='Должность создателя'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_created', to='core.position', verbose_name='Должность создателя'),
        ),
    ]
