# Generated by Django 6.0.2 on 2026-02-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('employees', '0002_employee_created_by_worktimerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_created', to='core.position', verbose_name='Должность создателя'),
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktimerecords_created', to='core.position', verbose_name='Должность создателя'),
        ),
    ]
