# Generated by Django 6.0.2 on 2026-02-11 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('forestry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип операции',
                'verbose_name_plural': 'Типы операций',
            },
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forestry.material', verbose_name='Материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='Склад')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.operationtype', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Запись операции',
                'verbose_name_plural': 'Учет операций',
                'indexes': [models.Index(fields=['date_time', 'operation_type'], name='operations__date_ti_a753cb_idx')],
            },
        ),
    ]
