# Generated by Django 6.0.2 on 2026-02-27 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operation_record', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_record_created', to='core.position', verbose_name='Должность создателя'),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operation_type', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='created_by_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_type_created', to='core.position', verbose_name='Должность создателя'),
        ),
    ]
