# Generated by Django 6.0.2 on 2026-03-17 12:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brigade_created_by_position_and_more'),
        ('forestry', '0003_cuttingarea_created_by_and_more'),
        ('operations', '0002_operationrecord_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrecord',
            name='cubic_meters',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Объем в кубических метрах', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Объем (м³)'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Площадь в квадратных метрах', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Количество в штуках', max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество (шт)'),
        ),
        migrations.AddIndex(
            model_name='operationrecord',
            index=models.Index(fields=['square_meters'], name='operations__square__e245f4_idx'),
        ),
        migrations.AddIndex(
            model_name='operationrecord',
            index=models.Index(fields=['cubic_meters'], name='operations__cubic_m_015837_idx'),
        ),
    ]
