# Generated by Django 6.0.2 on 2026-06-08 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operationrecord_cubic_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrecord',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время'),
        ),
    ]
