# Generated by Django 6.0.2 on 2026-07-20 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_operationrecord_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrecord',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Количество в штуках', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество (шт)'),
        ),
    ]
